workflows:
  node-multi-build:
    jobs:
      - '${jobName}'

jobs:
  '${jobName}':
    docker:
      - image: '${dockerImage}'
    steps:
      - checkout
      - run: sudo yarn global add gally
      - run: ga promote ${ciEnvBranchName}
