workflows:
  version: 2
  node-multi-build:
    jobs:
      - gally-create-pr
version: 2
jobs:
  gally-create-pr:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: sudo yarn global add gally
      - run: ga promote $CIRCLE_BRANCH
