workflows:
  version: 2
  node-multi-build:
    jobs:
      - gally-auto-merge:
          requires:
            - gally-create-pr
            - test-node-v10
            - test-node-v8.10
          filters:
            branches:
              only: /dependabot\/.*/
version: 2
jobs:
  gally-auto-merge:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run:
          name: Set PR number
          command: |
            echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
            source $BASH_ENV
            echo $CIRCLE_PR_NUMBER
      - checkout
      - run: sudo yarn global add gally
      - run: >-
          ga approve $CIRCLE_PR_NUMBER --condition
          "base.ref=dev&state=open&user.login=dependabot[bot]"
      - run: >-
          ga merge $CIRCLE_PR_NUMBER --condition
          "base.ref=dev&state=open&user.login=dependabot[bot]"
