version: 1
update_configs:
  - package_manager: "${packageManager}"
    directory: "/"
    update_schedule: "${updateSchedule}"

    target_branch: ${targetBranch}

    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"

    version_requirement_updates: increase_versions
