version: 1
update_configs:
  - package_manager: "${package-manager}"
    directory: "/"
    update_schedule: "${update-schedule}"

    target_branch: ${target-branch}

    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"

    version_requirement_updates: increase_versions
