workflows:
  node-multi-build:
    jobs:
      - ${jobName}: ${jobOptions}

jobs:
  ${jobName}:
    docker:
      - image: '${dockerImage}'
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: (git add . && git diff-index --quiet HEAD --) || (git status && exit 1);
